# Generated by Django 2.2.5 on 2020-04-22 21:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0002_auto_20200421_0020'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Address_type', models.CharField(choices=[('billing', 'Billing'), ('shipping', 'Shipping')], max_length=120)),
                ('Address_line_1', models.CharField(max_length=120)),
                ('Address_line_2', models.CharField(blank=True, max_length=120, null=True)),
                ('City', models.CharField(max_length=120)),
                ('Country', models.CharField(default='INDIA', max_length=120)),
                ('State', models.CharField(max_length=120)),
                ('Postal_code', models.CharField(max_length=120)),
                ('billing_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.BillingProfile')),
            ],
        ),
    ]
