# Generated by Django 2.2.5 on 2020-04-30 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_usersession'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usersession',
            old_name='session',
            new_name='session_key',
        ),
    ]
